### ISSUE TITLE
VirtualBox shared folder doesn't work well

### ISSUE THREAD

**Issue by ixkaito** [ailispaw/docker-root-packer#2]
## Environment:
- OSX 10.10.5
- Vagrant 1.7.4
- VirtualBox 5.0.10
- Vagrantfile:

``` ruby
Vagrant.configure(2) do |config|
  config.vm.define "docker-root"
  config.vm.box = "ailispaw/docker-root"

  if Vagrant.has_plugin?("vagrant-triggers") then
    config.trigger.after [:up, :resume] do
      info "Adjusting datetime after suspend and resume."
      run_remote "sudo sntp -4sSc pool.ntp.org; date"
    end
  end

  # Adjusting datetime before provisioning.
  config.vm.provision :shell, run: "always" do |sh|
    sh.inline = "sntp -4sSc pool.ntp.org; date"
  end

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder ".", "/vagrant", create: true

end
```
## Issue:

In the virtual machine: 
1. `vi /vagrant/test` and write `aaa`.
2. `cat /vagrant/test` displays `aaa`. No problem here.
3. `vi /vagrant/test` and change the content to `bbb`.
4. `cat /vagrant/test` displays `aaa` again. However, if `vi /vagrant/test`, it shows `bbb`.

**Comment by ailispaw** [comment]
Hi @ixkaito ,
Thank you for opening an issue.
I can reproduce it here on the same environment as yours.
I will figure this out.

BTW, on the host machine;

```
$ cat ./test
bbb
```

It's strange, isn't it?

**Comment by ailispaw** [comment]
It seems same as https://www.virtualbox.org/ticket/14746.

Not same but similar with that.
`echo 3 > /proc/sys/vm/drop_caches` after editing each time fixes the problem.

https://www.virtualbox.org/ticket/14424, too.

**Comment by ailispaw** [comment]
I found a patch for this issue at http://d.hatena.ne.jp/hiboma/20140320/1395312958 and applied it.
It is not perfect but it seems good for now, until VirtualBox GuestAddtions is fixed.
@ixkaito Thank you so much for giving me a heads up.

**Comment by ixkaito** [comment]
Thanks @ailispaw ! It works well now. Hope VirtualBox would be fixed in the future.
I'm planning to use DockerRoot for my project [Wocker](http://wckr.github.io/).
Great work!

**Comment by ailispaw** [comment]
Thank you so much for trying it.
Please feel free to ask me if you need something.

**Comment by ailispaw** [comment]
This seems to fix http://qiita.com/miyumiyu/items/2fe4032ce126b2c41f5c with https://github.com/ailispaw/docker-root-pkg#perl as well.

**Comment by ailispaw** [comment]
FYI: DockerRoot box works fine in the case of https://www.virtualbox.org/ticket/14920.
